---
collections:
  - name: community.general
    version: 6.2.0

  - name: ibm.power_aix
    version: 1.5.1

  - name: amazon.aws
    version: 3.2.0 

#  - name: ansible.controller
#    version: 4.2.1

  - name: ansible.netcommon
    version: 3.1.1

  - name: ansible.network
    version: 1.2.0

  - name: ansible.posix
    version: 1.3.0

  - name: ansible.security
    version: 1.0.0

  - name: ansible.utils
    version: 2.6.1

  - name: ansible.windows
    version: 1.9.0

  - name: ansible.yang
    version: 1.0.0

  - name: arista.eos
    version: 5.0.0

  - name: cisco.asa
    version: 3.0.0

  - name: cisco.ios
    version: 3.0.0

  - name: cisco.iosxr
    version: 3.0.0

  - name: cisco.nxos
    version: 3.0.0

  - name: cloud.common
    version: 2.1.1

  - name: frr.frr
    version: 2.0.0

  - name: ibm.qradar
    version: 2.0.0

  - name: junipernetworks.junos
    version: 3.0.0

  - name: kubernetes.core
    version: 2.2.3

  - name: openvswitch.openvswitch
    version: 2.1.0

#  - name: redhat.insights
#    version: 1.0.7

#  - name: redhat.openshift
#    version: 2.1.0

#  - name: redhat.rhv
#    version: 1.6.5

#  - name: redhat.satellite
#    version: 3.3.0

  - name: servicenow.itsm
    version: 1.3.3

  - name: splunk.es
    version: 2.0.0

  - name: trendmicro.deepsec
    version: 2.0.0

  - name: vmware.vmware_rest
    version: 2.1.5

  - name: vyos.vyos
    version: 3.0.0
